### ISSUE TITLE
unity prefabs being lost

### ISSUE THREAD

**Issue by DestinedDotCom** [vaughanknight/RadialControllerUnityBridge#2]
When opening the demo scene all the prefabs and scripts are missing. 

Think your setting in unity are incorrect for use with git. Go to editor settings (off the edit menu) and change asset serialization from mixed to forced text to fix the issue. Then push again and it should all work!

Thanks
James

**Comment by vaughanknight** [comment]
Try now.  Have just pushed those changes.

**Comment by DestinedDotCom** [comment]
Still doesn't work, I also can't see any of the meta files in the git when just browsing it online

![example](https://cloud.githubusercontent.com/assets/23441589/25777463/951cd770-3321-11e7-8677-d8eb01f27538.jpg)

When a unity git is setup correctly you see these .meta files (which I think your one is ignoring because they are binary). Above is an example from one of mine so you can see what it looks like. 

If you pull back over your current project it will work. Try cloning someone else to see the issue. I changed to 2017 b because initially that is what I thought the issue was, but that doesn't fix it. 

This is what it looks like on mine
![lookslike](https://cloud.githubusercontent.com/assets/23441589/25777482/175e2e32-3322-11e7-828f-dc83d2d4c756.jpg)

**Comment by vaughanknight** [comment]
Strange, was working on mine without the .meta files so I put them in the git ignore.  Will remove from the ignore.

**Comment by vaughanknight** [comment]
Should be sync'd, try now.

**Comment by DestinedDotCom** [comment]
thank you, works now!!!
![works](https://cloud.githubusercontent.com/assets/23441589/25777781/b8fb6ac6-332b-11e7-8e0b-4920225a7a05.jpg)

**Comment by vaughanknight** [comment]
All fixed and working :)
